version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ticket-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ticket_db
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ticket-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
